/**
 * Hindi translations
 */
export default {
  app: { name: 'DriveLegal', tagline: 'अपने सड़क कानून जानें' },
  common: {
    search: 'खोजें',
    filter: 'फ़िल्टर',
    sort: 'क्रमबद्ध करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    apply: 'लागू करें',
    clear: 'साफ़ करें',
    retry: 'पुनः प्रयास करें',
    loading: 'लोड हो रहा है...',
    error: 'कुछ गलत हो गया',
    offline: 'आप ऑफ़लाइन हैं',
    online: 'ऑनलाइन',
    noResults: 'कोई परिणाम नहीं मिला',
    seeAll: 'सभी देखें',
    back: 'वापस',
    next: 'अगला',
    skip: 'छोड़ें',
    done: 'पूर्ण',
    close: 'बंद करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    share: 'साझा करें',
  },
  onboarding: {
    slide1Title: 'स्थानीय यातायात कानून तुरंत प्राप्त करें',
    slide1Desc: 'अपने सटीक स्थान के लिए राज्य-विशिष्ट यातायात नियम, जुर्माना और कानून प्राप्त करें।',
    slide2Title: 'जुर्माना होने से पहले जानें',
    slide2Desc: 'किसी भी राज्य में किसी भी उल्लंघन का सटीक जुर्माना जानें।',
    slide3Title: 'ऑफ़लाइन भी काम करता है',
    slide3Desc: 'अपने राज्य के कानून ऑफ़लाइन एक्सेस के लिए डाउनलोड करें।',
    getStarted: 'शुरू करें',
    skipForNow: 'अभी छोड़ें',
    setLocation: 'अपना स्थान सेट करें',
    useCurrentLocation: 'वर्तमान स्थान का उपयोग करें (GPS)',
    orSelectManually: '— या मैन्युअल रूप से चुनें —',
    selectCountry: 'देश चुनें',
    selectState: 'राज्य चुनें',
    selectCity: 'शहर चुनें',
    continue: 'जारी रखें',
    selectLanguage: 'भाषा चुनें',
  },
  home: {
    greeting: 'आपको क्या जानना है?',
    searchPlaceholder: 'कानून, उल्लंघन, जुर्माना खोजें...',
    quickActions: 'त्वरित कार्य',
    chatWithAI: 'AI से चैट करें',
    chatDesc: 'कोई भी यातायात कानून प्रश्न पूछें',
    fineCalculator: 'जुर्माना कैलकुलेटर',
    calcDesc: 'चालान राशि का अनुमान',
    browseLaws: 'कानून ब्राउज़ करें',
    lawsDesc: 'पूर्ण लाइब्रेरी देखें',
    emergency: 'SOS / आपातकालीन',
    emergencyDesc: 'हेल्पलाइन त्वरित एक्सेस',
    todaysFact: 'आज का तथ्य',
    didYouKnow: '💡 क्या आप जानते हैं?',
    commonViolations: 'आपके क्षेत्र में सामान्य उल्लंघन',
    recentFines: 'निकट में जारी हालिया जुर्माना',
    live: 'लाइव',
    safetyScore: 'आपका सुरक्षा स्कोर',
    goodDriver: 'अच्छा ड्राइवर',
    improveScore: 'अपना स्कोर बेहतर करने के लिए क्विज़ पूरा करें',
  },
  chat: {
    title: 'DriveLegal AI',
    contextLabel: 'इसके लिए जवाब दे रहे हैं',
    placeholder: 'यातायात कानून के बारे में पूछें...',
    welcome: 'नमस्ते! मैं आपका DriveLegal AI सहायक हूं। मैं आपके स्थान के लिए यातायात कानूनों, जुर्मानों और उल्लंघनों के बारे में प्रश्नों का उत्तर दे सकता हूं।',
    whatToKnow: 'आप क्या जानना चाहेंगे?',
    offlineMode: 'ऑफ़लाइन मोड — कैश्ड उत्तर दिखा रहे हैं',
    queued: 'संदेश कतार में — ऑनलाइन होने पर भेजा जाएगा',
  },
  calculator: {
    title: 'जुर्माना कैलकुलेटर',
    violationType: 'उल्लंघन का प्रकार',
    selectViolation: 'उल्लंघन चुनें...',
    vehicleType: 'वाहन का प्रकार',
    offenceNumber: 'अपराध संख्या',
    firstOffence: 'पहला अपराध',
    repeatOffence: 'दोहरा अपराध',
    location: 'स्थान (स्वतः पता लगाया गया)',
    calculateFine: 'जुर्माना गणना करें',
    fineBreakdown: 'जुर्माना विवरण',
    baseFine: 'मूल जुर्माना',
    surcharge: 'राज्य अधिभार',
    compounding: 'कंपाउंडिंग शुल्क',
    totalPayable: 'कुल भुगतान योग्य',
    licencePoints: 'लाइसेंस अंक कटौती',
    lawReference: 'कानून संदर्भ',
    compare: 'तुलना करें',
    payOnline: 'ऑनलाइन भुगतान करें',
    selectViolationError: 'कृपया एक उल्लंघन प्रकार चुनें।',
  },
  laws: {
    title: 'कानून लाइब्रेरी',
    searchPlaceholder: 'कानून, धारा, कीवर्ड खोजें...',
    all: 'सभी',
    national: 'राष्ट्रीय',
    state: 'राज्य',
    city: 'शहर',
    viewDetails: 'विवरण देखें',
    bookmark: 'बुकमार्क',
    compareLaws: 'कानूनों की तुलना करें',
    officialText: 'आधिकारिक कानूनी पाठ',
    simplifiedExplanation: 'सरल व्याख्या',
    amendments: 'संशोधन समयरेखा',
    relatedViolations: 'संबंधित उल्लंघन',
    fineSchedule: 'जुर्माना अनुसूची',
    updated: 'अपडेटेड',
  },
  profile: {
    title: 'प्रोफ़ाइल और सेटिंग्स',
    myVehicles: 'मेरे वाहन',
    addVehicle: 'वाहन जोड़ें',
    savedHistory: 'सहेजा गया और इतिहास',
    savedLaws: 'सहेजे गए कानून',
    savedCalculations: 'सहेजी गई गणनाएं',
    preferences: 'प्राथमिकताएं',
    country: 'देश',
    theme: 'थीम',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    accessibility: 'अभिगम्यता',
    offlineData: 'ऑफ़लाइन डेटा',
    about: 'जानकारी और कानूनी',
    sendFeedback: 'प्रतिक्रिया भेजें',
    fontSize: 'फ़ॉन्ट आकार',
    highContrast: 'उच्च कंट्रास्ट',
    reducedMotion: 'कम एनिमेशन',
  },
  emergency: {
    title: 'आपातकालीन और त्वरित संदर्भ',
    contacts: 'आपातकालीन संपर्क',
    callNow: 'अभी कॉल करें',
    quickReference: 'त्वरित संदर्भ',
    accidentChecklist: 'दुर्घटना चेकलिस्ट',
    accidentDesc: 'दुर्घटना के बाद क्या करें — चरण दर चरण',
    rights: 'ट्रैफिक स्टॉप के दौरान आपके अधिकार',
    rightsDesc: 'पुलिस द्वारा रोके जाने पर अपने अधिकार जानें',
    documents: 'आवश्यक दस्तावेज़ चेकलिस्ट',
    documentsDesc: 'गाड़ी चलाते समय रखने योग्य दस्तावेज़',
    nearestStation: 'निकटतम ट्रैफिक पुलिस स्टेशन',
    nearestDesc: 'अपने स्थान के निकटतम स्टेशन खोजें',
  },
  notifications: {
    title: 'सूचनाएं',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    clearAll: 'सभी साफ़ करें',
    noNotifications: 'अभी तक कोई सूचना नहीं',
    lawChanges: 'कानून परिवर्तन',
    reminders: 'अनुस्मारक',
    safetyTips: 'सुरक्षा सुझाव',
    appUpdates: 'ऐप अपडेट',
  },
};
