/**
 * Malayalam translations
 */
export default {
  app: { name: 'DriveLegal', tagline: 'നിങ്ങളുടെ റോഡ് നിയമങ്ങൾ അറിയുക' },
  common: {
    search: 'തിരയുക',
    filter: 'ഫിൽട്ടർ',
    sort: 'ക്രമീകരിക്കുക',
    save: 'സൂക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    apply: 'ബാധകമാക്കുക',
    clear: 'ഒഴിവാക്കുക',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    error: 'എന്തോ തകരാർ സംഭവിച്ചു',
    offline: 'നിങ്ങൾ ഓഫ്‌ലൈനിലാണ്',
    online: 'ഓൺലൈൻ',
    noResults: 'ഫലങ്ങൾ ഒന്നും ലഭ്യമല്ല',
    seeAll: 'എല്ലാം കാണുക',
    back: 'പിന്നോട്ട്',
    next: 'അടുത്തത്',
    skip: 'ഒഴിവാക്കുക',
    done: 'പൂർത്തിയായി',
    close: 'അടയ്ക്കുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'തിരുത്തുക',
    add: 'ചേർക്കുക',
    share: 'പങ്കിടുക',
  },
  onboarding: {
    slide1Title: 'പ്രാദേശിക ട്രാഫിക് നിയമങ്ങൾ ഉടൻ നേടുക',
    slide1Desc: 'നിങ്ങളുടെ സ്ഥലത്തിന് അനുയോജ്യമായ ട്രാഫിക് നിയമങ്ങളും പിഴകളും എളുപ്പത്തിൽ ആക്സസ് ചെയ്യുക.',
    slide2Title: 'പിഴ തുകകൾ മുൻകൂട്ടി കണക്കാക്കുക',
    slide2Desc: 'ഏതൊരു നിയമലംഘനത്തിനും എത്ര പിഴ ഈടാക്കുമെന്ന് മുൻകൂട്ടി അറിയുക.',
    slide3Title: 'ഓഫ്‌ലൈനിലും പ്രവർത്തിക്കും',
    slide3Desc: 'ഓഫ്‌ലൈൻ ആക്‌സസിനായി നിങ്ങളുടെ സംസ്ഥാനത്തെ റോഡ് നിയമങ്ങൾ ഡൗൺലോഡ് ചെയ്യുക.',
    getStarted: 'ആരംഭിക്കുക',
    skipForNow: 'ഇപ്പൊഴത്തേക്ക് ഒഴിവാക്കുക',
    setLocation: 'നിങ്ങളുടെ സ്ഥലം നിശ്ചയിക്കുക',
    useCurrentLocation: 'നിലവിലെ സ്ഥലം ഉപയോഗിക്കുക (GPS)',
    orSelectManually: '— അല്ലെങ്കിൽ സ്വയം തിരഞ്ഞെടുക്കുക —',
    selectCountry: 'രാജ്യം തിരഞ്ഞെടുക്കുക',
    selectState: 'സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    selectCity: 'നഗരം തിരഞ്ഞെടുക്കുക',
    continue: 'തുടരുക',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  },
  home: {
    greeting: 'നിങ്ങൾക്ക് എന്താണ് അറിയേണ്ടത്?',
    searchPlaceholder: 'നിയമങ്ങൾ, നിയമലംഘനങ്ങൾ, പിഴകൾ എന്നിവ തിരയുക...',
    quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    chatWithAI: 'AI ചാറ്റ് ചെയ്യുക',
    chatDesc: 'ട്രാഫിക് നിയമങ്ങളെക്കുറിച്ച് ചോദിക്കുക',
    fineCalculator: 'പിഴ കാൽക്കുലേറ്റർ',
    calcDesc: 'ചെല്ലാൻ തുക കണക്കാക്കുക',
    browseLaws: 'നിയമങ്ങൾ കാണുക',
    lawsDesc: 'മുഴുവൻ ലൈബ്രറിയും പരിശോധിക്കുക',
    emergency: 'SOS / അടിയന്തിരം',
    emergencyDesc: 'അടിയന്തിര ഹെൽപ്പ്‌ലൈൻ നമ്പറുകൾ',
    todaysFact: 'ഇന്നത്തെ വസ്തുത',
    didYouKnow: '💡 നിങ്ങൾക്കറിയാമോ?',
    commonViolations: 'നിങ്ങളുടെ പ്രദേശത്തെ പൊതുവായ നിയമലംഘനങ്ങൾ',
    recentFines: 'സമീപത്തുണ്ടായ പിഴ വിവരങ്ങൾ',
    live: 'ലൈവ്',
    safetyScore: 'നിങ്ങളുടെ സുരക്ഷാ സ്കോർ',
    goodDriver: 'നല്ല ഡ്രൈവർ',
    improveScore: 'സ്കോർ ഉയർത്താൻ ക്വിസ് പൂർത്തിയാക്കുക',
  },
  chat: {
    title: 'DriveLegal AI',
    contextLabel: 'മറുപടി നൽകുന്നു',
    placeholder: 'റോഡ് നിയമങ്ങളെക്കുറിച്ച് ചോദിക്കുക...',
    welcome: 'നമസ്കാരം! ഞാൻ നിങ്ങളുടെ DriveLegal AI സഹായിയാണ്. ട്രാഫിക് നിയമങ്ങൾ, പിഴകൾ എന്നിവയെക്കുറിച്ചുള്ള ചോദ്യങ്ങൾക്ക് ഞാൻ മറുപടി നൽകും.',
    whatToKnow: 'നിങ്ങൾക്ക് എന്താണ് അറിയേണ്ടത്?',
    offlineMode: 'ഓഫ്‌ലൈൻ മോഡ് — സേവ് ചെയ്ത മറുപടികൾ',
    queued: 'സന്ദേശം ക്യൂവിലാണ് — ഓൺലൈൻ ആകുമ്പോൾ അയയ്ക്കും',
  },
  calculator: {
    title: 'പിഴ കാൽക്കുലേറ്റർ',
    violationType: 'നിയമലംഘന തരം',
    selectViolation: 'നിയമലംഘനം തിരഞ്ഞെടുക്കുക...',
    vehicleType: 'വാഹന തരം',
    offenceNumber: 'കുറ്റകൃത്യ നമ്പർ',
    firstOffence: 'ആദ്യ തവണ കുറ്റം',
    repeatOffence: 'ആവർത്തിച്ചുള്ള കുറ്റം',
    location: 'സ്ഥലം (ഓട്ടോമാറ്റിക്കായി കണ്ടെത്തിയത്)',
    calculateFine: 'പിഴ കണക്കാക്കുക',
    fineBreakdown: 'പിഴയുടെ വിശദാംശങ്ങൾ',
    baseFine: 'അടിസ്ഥാന പിഴ',
    surcharge: 'സംസ്ഥാന സർചാർജ്',
    compounding: 'കോമ്പൗണ്ടിംഗ് ഫീസ്',
    totalPayable: 'ആകെ അടയ്ക്കേണ്ട തുക',
    licencePoints: 'ലൈസൻസ് പോയിന്റ് കുറവ്',
    lawReference: 'നിയമ പരാമർശം',
    compare: 'താരതമ്യം ചെയ്യുക',
    payOnline: 'ഓൺലൈനായി അടയ്ക്കുക',
    selectViolationError: 'ദയവായി നിയമലംഘന തരം തിരഞ്ഞെടുക്കുക.',
  },
  laws: {
    title: 'നിയമ ലൈബ്രറി',
    searchPlaceholder: 'നിയമങ്ങൾ, വകുപ്പുകൾ, കീവേഡുകൾ തിരയുക...',
    all: 'എല്ലാം',
    national: 'ദേശീയം',
    state: 'സംസ്ഥാനം',
    city: 'നഗരം',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    bookmark: 'ബുക്ക്മാർക്ക് ചെയ്യുക',
    compareLaws: 'നിയമങ്ങൾ താരതമ്യം ചെയ്യുക',
    officialText: 'ഔദ്യോഗിക നിയമ പാഠം',
    simplifiedExplanation: 'ലളിതമായ വിശദീകരണം',
    amendments: 'ഭേദഗതികൾ',
    relatedViolations: 'ബന്ധപ്പെട്ട നിയമലംഘനങ്ങൾ',
    fineSchedule: 'പിഴ പട്ടിക',
    updated: 'പുതുക്കിയത്',
  },
  profile: {
    title: 'പ്രൊഫൈലും ക്രമീകരണങ്ങളും',
    myVehicles: 'എന്റെ വാഹനങ്ങൾ',
    addVehicle: 'വാഹനം ചേർക്കുക',
    savedHistory: 'സേവ് ചെയ്തവയും ചരിത്രവും',
    savedLaws: 'സേവ് ചെയ്ത നിയമങ്ങൾ',
    savedCalculations: 'സേവ് ചെയ്ത കണക്കുകൂട്ടലുകൾ',
    preferences: 'മുൻഗണനകൾ',
    country: 'രാജ്യം',
    theme: 'തീം',
    language: 'ഭാഷ',
    notifications: 'അറിയിപ്പുകൾ',
    accessibility: 'ആക്സസിബിലിറ്റി',
    offlineData: 'ഓഫ്‌ലൈൻ ഡാറ്റ',
    about: 'വിവരങ്ങൾ & നിയമപരം',
    sendFeedback: 'അഭിപ്രായം അയയ്ക്കുക',
    fontSize: 'അക്ഷര വലിപ്പം',
    highContrast: 'ഹൈ കോൺട്രാസ്റ്റ്',
    reducedMotion: 'കുറഞ്ഞ ആനിമേഷൻ',
  },
  emergency: {
    title: 'അടിയന്തിരാവസ്ഥയും ദ്രുത റഫറൻസും',
    contacts: 'അടിയന്തിര കോൺടാക്റ്റുകൾ',
    callNow: 'വിളിക്കുക',
    quickReference: 'ദ്രുത റഫറൻസ്',
    accidentChecklist: 'അപകട ചെക്ക്‌ലിസ്റ്റ്',
    accidentDesc: 'അപകടത്തിന് ശേഷം ചെയ്യേണ്ട കാര്യങ്ങൾ',
    rights: 'ട്രാഫിക് സ്റ്റോപ്പ് സമയത്തെ നിങ്ങളുടെ അവകാശങ്ങൾ',
    rightsDesc: 'പോലീസ് തടയുമ്പോൾ നിങ്ങളുടെ അവകാശങ്ങൾ മനസ്സിലാക്കുക',
    documents: 'ആവശ്യമായ രേഖകളുടെ ചെക്ക്‌ലിസ്റ്റ്',
    documentsDesc: 'ഡ്രൈവിംഗ് ചെയ്യുമ്പോൾ സൂക്ഷിക്കേണ്ട രേഖകൾ',
    nearestStation: 'അടുത്തുള്ള ട്രാഫിക് പോലീസ് സ്റ്റേഷൻ',
    nearestDesc: 'നിങ്ങളുടെ സ്ഥലത്തിനടുത്തുള്ള സ്റ്റേഷൻ കണ്ടെത്തുക',
  },
  notifications: {
    title: 'അറിയിപ്പുകൾ',
    markAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    clearAll: 'എല്ലാം ഒഴിവാക്കുക',
    noNotifications: 'അറിയിപ്പുകൾ ലഭ്യമല്ല',
    lawChanges: 'നിയമ ഭേദഗതികൾ',
    reminders: 'ഓർമ്മപ്പെടുത്തലുകൾ',
    safetyTips: 'സുരക്ഷാ നുറുങ്ങുകൾ',
    appUpdates: 'ആപ്പ് അപ്‌ഡേറ്റുകൾ',
  },
};
