/**
 * Telugu translations
 */
export default {
  app: { name: 'DriveLegal', tagline: 'మీ రహదారి చట్టాలను తెలుసుకోండి' },
  common: {
    search: 'వెతకండి',
    filter: 'ఫిల్టర్',
    sort: 'క్రమబద్ధీకరించు',
    save: 'సేవ్ చేయి',
    cancel: 'రద్దు చేయి',
    apply: 'వర్తింపజేయి',
    clear: 'తుడిచివేయి',
    retry: 'మళ్ళీ ప్రయత్నించు',
    loading: 'లోడ్ అవుతోంది...',
    error: 'ఏదో తప్పు జరిగింది',
    offline: 'మీరు ఆఫ్-లైన్ లో ఉన్నారు',
    online: 'ఆన్-లైన్',
    noResults: 'ఫలితాలు లేవు',
    seeAll: 'అన్నీ చూడండి',
    back: 'వెనుకకు',
    next: 'తరువాత',
    skip: 'వదిలివేయి',
    done: 'పూర్తయింది',
    close: 'మూసివేయి',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    add: 'జోడించు',
    share: 'భాగస్వామ్యం చేయి',
  },
  onboarding: {
    slide1Title: 'స్థానిక ట్రాఫిక్ చట్టాలను వెంటనే పొందండి',
    slide1Desc: 'మీ ప్రాంతానికి సంబంధించిన ట్రాఫిక్ నిబంధనలు, జరిమానాలు మరియు చట్టాలను సులభంగా యాక్సెస్ చేయండి.',
    slide2Title: 'జరిమానాలను ముందే లెక్కించండి',
    slide2Desc: 'ఏదైనా నిబంధన ఉల్లంఘనకు ఎంత జరిమానా పడుతుందో ముందే తెలుసుకోండి.',
    slide3Title: 'ఆఫ్-లైన్ లో కూడా పనిచేస్తుంది',
    slide3Desc: 'ఆఫ్-లైన్ యాక్సెస్ కోసం మీ రాష్ట్ర ట్రాఫిక్ చట్టాలను డౌన్-లోడ్ చేసుకోండి.',
    getStarted: 'ప్రారంభించండి',
    skipForNow: 'ఇప్పటికి వదిలివేయి',
    setLocation: 'మీ ప్రాంతాన్ని సెట్ చేయండి',
    useCurrentLocation: 'ప్రస్తుత ప్రాంతాన్ని ఉపయోగించండి (GPS)',
    orSelectManually: '— లేదా మాన్యువల్ గా ఎంచుకోండి —',
    selectCountry: 'దేశాన్ని ఎంచుకోండి',
    selectState: 'రాష్ట్రాన్ని ఎంచుకోండి',
    selectCity: 'నగరాన్ని ఎంచుకోండి',
    continue: 'కొనసాగించు',
    selectLanguage: 'భాషను ఎంచుకోండి',
  },
  home: {
    greeting: 'మీకు ఏమి తెలియాలి?',
    searchPlaceholder: 'చట్టాలు, ఉల్లంఘనలు, జరిమానాలను వెతకండి...',
    quickActions: 'త్వరిత చర్యలు',
    chatWithAI: 'AI తో చాట్ చేయండి',
    chatDesc: 'ట్రాఫిక్ చట్టాల గురించి ఏదైనా అడగండి',
    fineCalculator: 'జరిమానాల క్యాలిక్యులేటర్',
    calcDesc: 'చలాన్ మొత్తాన్ని అంచనా వేయండి',
    browseLaws: 'చట్టాలను బ్రౌజ్ చేయండి',
    lawsDesc: 'పూర్తి లైబ్రరీని చూడండి',
    emergency: 'SOS / అత్యవసరం',
    emergencyDesc: 'అత్యవసర హెల్ప్-లైన్ నంబర్లు',
    todaysFact: 'ఈరోజు విశేషం',
    didYouKnow: '💡 మీకు తెలుసా?',
    commonViolations: 'మీ ప్రాంతంలో సాధారణ ఉల్లంఘనలు',
    recentFines: 'సమీపంలో జారీ చేయబడిన జరిమానాలు',
    live: 'లైవ్',
    safetyScore: 'మీ సేఫ్టీ స్కోర్',
    goodDriver: 'మంచి డ్రైవర్',
    improveScore: 'స్కోరు మెరుగుపరచడానికి క్విజ్ పూర్తి చేయండి',
  },
  chat: {
    title: 'DriveLegal AI',
    contextLabel: 'సమాధానం ఇస్తోంది',
    placeholder: 'ట్రాఫిక్ చట్టాల గురించి అడగండి...',
    welcome: 'నమస్కారం! నేను మీ DriveLegal AI సహాయకుడిని. మీ ప్రాంతానికి సంబంధించిన ట్రాఫిక్ చట్టాలు మరియు జరిమానాల గురించి మీ సందేహాలను నివృత్తి చేస్తాను.',
    whatToKnow: 'మీరు ఏమి తెలుసుకోవాలనుకుంటున్నారు?',
    offlineMode: 'ఆఫ్-లైన్ మోడ్ — సేవ్ చేసిన సమాధానాలు',
    queued: 'సందేశం క్యూలో ఉంది — ఆన్-లైన్ వచ్చినప్పుడు పంపబడుతుంది',
  },
  calculator: {
    title: 'జరిమానాల క్యాలిక్యులేటర్',
    violationType: 'ఉల్లంఘన రకం',
    selectViolation: 'ఉల్లంఘనను ఎంచుకోండి...',
    vehicleType: 'వాహనం రకం',
    offenceNumber: 'నేరం సంఖ్య',
    firstOffence: 'మొదటి సారి నేరం',
    repeatOffence: 'మళ్ళీ చేసిన నేరం',
    location: 'ప్రాంతం (ఆటోమేటిక్ గా గుర్తించబడింది)',
    calculateFine: 'జరిమానా లెక్కించు',
    fineBreakdown: 'జరిమానా వివరాలు',
    baseFine: 'బేసిక్ జరిమానా',
    surcharge: 'రాష్ట్ర సర్-ఛార్జ్',
    compounding: 'కాంపౌండింగ్ ఫీజు',
    totalPayable: 'చెల్లించాల్సిన మొత్తం',
    licencePoints: 'లైసెన్స్ పాయింట్ల తగ్గింపు',
    lawReference: 'చట్టం సూచన',
    compare: 'పోల్చండి',
    payOnline: 'ఆన్-లైన్ లో చెల్లించండి',
    selectViolationError: 'దయచేసి ఉల్లంఘన రకాన్ని ఎంచుకోండి.',
  },
  laws: {
    title: 'చట్టాల లైబ్రరీ',
    searchPlaceholder: 'చట్టాలు, సెక్షన్లు, కీ-వర్డ్స్ వెతకండి...',
    all: 'అన్నీ',
    national: 'జాతీయ',
    state: 'రాష్ట్ర',
    city: 'నగర',
    viewDetails: 'వివరాలు చూడండి',
    bookmark: 'బుక్-మార్క్ చేయి',
    compareLaws: 'చట్టాలను పోల్చండి',
    officialText: 'అధికారిక చట్ట పాఠం',
    simplifiedExplanation: 'సులభమైన వివరణ',
    amendments: 'సవరణల కాలక్రమం',
    relatedViolations: 'సంబంధిత ఉల్లంఘనలు',
    fineSchedule: 'జరిమానాల పట్టిక',
    updated: 'అప్-డేట్ చేయబడింది',
  },
  profile: {
    title: 'ప్రొఫైల్ & సెట్టింగ్స్',
    myVehicles: 'నా వాహనాలు',
    addVehicle: 'వాహనాన్ని జోడించు',
    savedHistory: 'సేవ్ చేసినవి & చరిత్ర',
    savedLaws: 'సేవ్ చేసిన చట్టాలు',
    savedCalculations: 'సేవ్ చేసిన లెక్కలు',
    preferences: 'ప్రాధాన్యతలు',
    country: 'దేశం',
    theme: 'థీమ్',
    language: 'భాష',
    notifications: 'నోటిఫికేషన్లు',
    accessibility: 'యాక్సెస్-బిలిటీ',
    offlineData: 'ఆఫ్-లైన్ డేటా',
    about: 'గురించి & చట్టపరమైన',
    sendFeedback: 'అభిప్రాయాన్ని పంపండి',
    fontSize: 'ఫాంట్ సైజు',
    highContrast: 'హై కాంట్రాస్ట్',
    reducedMotion: 'తగ్గించిన యానిమేషన్',
  },
  emergency: {
    title: 'అత్యవసరం & త్వరిత సూచన',
    contacts: 'అత్యవసర కాంటాక్ట్స్',
    callNow: 'ఇప్పుడే కాల్ చేయండి',
    quickReference: 'త్వరిత సూచన',
    accidentChecklist: 'ప్రమాద తనిఖీ జాబితా',
    accidentDesc: 'ప్రమాదం జరిగిన తర్వాత ఏమి చేయాలి అనేదానికి గైడ్',
    rights: 'ట్రాఫిక్ స్టాప్ సమయంలో మీ హక్కులు',
    rightsDesc: 'పోలీసులు ఆపినప్పుడు మీ హక్కులను తెలుసుకోండి',
    documents: 'అవసరమైన డాక్యుమెంట్ల జాబితా',
    documentsDesc: 'డ్రైవింగ్ చేసేటప్పుడు మీతో ఉండవలసిన పత్రాలు',
    nearestStation: 'సమీప ట్రాఫిక్ పోలీస్ స్టేషన్',
    nearestDesc: 'మీ ప్రాంతానికి సమీపంలో ఉన్న పోలీస్ స్టేషన్ ను కనుగొనండి',
  },
  notifications: {
    title: 'నోటిఫికేషన్లు',
    markAllRead: 'అన్నీ చదివినట్లుగా మార్క్ చేయి',
    clearAll: 'అన్నీ తుడిచివేయి',
    noNotifications: 'ఇంకా నోటిఫికేషన్లు లేవు',
    lawChanges: 'చట్టంలో మార్పులు',
    reminders: 'రిమైండర్లు',
    safetyTips: 'భద్రతా చిట్కాలు',
    appUpdates: 'యాప్ అప్-డేట్లు',
  },
};
