/**
 * English translations
 */
export default {
  app: { name: 'DriveLegal', tagline: 'Know Your Road Laws' },
  common: {
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    save: 'Save',
    cancel: 'Cancel',
    apply: 'Apply',
    clear: 'Clear',
    retry: 'Retry',
    loading: 'Loading...',
    error: 'Something went wrong',
    offline: 'You are offline',
    online: 'Online',
    noResults: 'No results found',
    seeAll: 'See All',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    share: 'Share',
  },
  onboarding: {
    slide1Title: 'Get Local Traffic Laws Instantly',
    slide1Desc: 'Access state-specific traffic regulations, fines, and rules for your exact location — simplified for everyday drivers.',
    slide2Title: 'Calculate Fines Before They Happen',
    slide2Desc: "Know the exact penalty for any violation, in any state, before it costs you — so you're never caught off guard.",
    slide3Title: 'Works Offline, Anywhere',
    slide3Desc: "Download your state's laws for offline access. Whether you have signal or not, DriveLegal has you covered.",
    getStarted: 'Get Started',
    skipForNow: 'Skip for now',
    setLocation: 'Set Your Location',
    useCurrentLocation: 'Use Current Location (GPS)',
    orSelectManually: '— or select manually —',
    selectCountry: 'Select Country',
    selectState: 'Select State',
    selectCity: 'Select City',
    continue: 'Continue',
    selectLanguage: 'Select Language',
  },
  home: {
    greeting: 'What do you need to know?',
    searchPlaceholder: 'Search laws, violations, fines...',
    quickActions: 'Quick Actions',
    chatWithAI: 'Chat with AI',
    chatDesc: 'Ask any traffic law question',
    fineCalculator: 'Fine Calculator',
    calcDesc: 'Estimate challan amount',
    browseLaws: 'Browse Laws',
    lawsDesc: 'Explore full library',
    emergency: 'SOS / Emergency',
    emergencyDesc: 'Quick access helplines',
    todaysFact: "Today's Fact",
    didYouKnow: '💡 Did You Know?',
    commonViolations: 'Common Violations in Your Area',
    recentFines: 'Recent fines issued nearby',
    live: 'Live',
    safetyScore: 'Your Safety Score',
    goodDriver: 'Good Driver',
    improveScore: 'Complete a quiz to improve your score',
  },
  chat: {
    title: 'DriveLegal AI',
    contextLabel: 'Answering for',
    placeholder: 'Ask about a traffic law...',
    welcome: "Hi! I'm your DriveLegal AI assistant. I can answer questions about traffic laws, fines, and violations specific to your location.",
    whatToKnow: 'What would you like to know?',
    offlineMode: 'Offline Mode — Showing cached answers',
    queued: 'Message queued — will send when online',
  },
  calculator: {
    title: 'Fine Calculator',
    violationType: 'Violation Type',
    selectViolation: 'Select violation...',
    vehicleType: 'Vehicle Type',
    offenceNumber: 'Offence Number',
    firstOffence: 'First Offence',
    repeatOffence: 'Repeat Offence',
    location: 'Location (auto-detected)',
    calculateFine: 'Calculate Fine',
    fineBreakdown: 'Fine Breakdown',
    baseFine: 'Base Fine',
    surcharge: 'State Surcharge',
    compounding: 'Compounding Fee',
    totalPayable: 'Total Payable',
    licencePoints: 'Licence Points Deducted',
    lawReference: 'Law Reference',
    compare: 'Compare',
    payOnline: 'Pay Online',
    selectViolationError: 'Please select a violation type.',
  },
  laws: {
    title: 'Laws Library',
    searchPlaceholder: 'Search laws, sections, keywords...',
    all: 'All',
    national: 'National',
    state: 'State',
    city: 'City',
    viewDetails: 'View Details',
    bookmark: 'Bookmark',
    compareLaws: 'Compare Laws',
    officialText: 'Official Legal Text',
    simplifiedExplanation: 'Simplified Explanation',
    amendments: 'Amendments Timeline',
    relatedViolations: 'Related Violations',
    fineSchedule: 'Fine Schedule',
    updated: 'Updated',
  },
  profile: {
    title: 'Profile & Settings',
    myVehicles: 'My Vehicles',
    addVehicle: 'Add vehicle',
    savedHistory: 'Saved & History',
    savedLaws: 'Saved Laws',
    savedCalculations: 'Saved Calculations',
    preferences: 'Preferences',
    country: 'Country',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    accessibility: 'Accessibility',
    offlineData: 'Offline Data',
    about: 'About & Legal',
    sendFeedback: 'Send Feedback',
    fontSize: 'Font Size',
    highContrast: 'High Contrast',
    reducedMotion: 'Reduced Motion',
  },
  emergency: {
    title: 'Emergency & Quick Reference',
    contacts: 'Emergency Contacts',
    callNow: 'Call Now',
    quickReference: 'Quick Reference',
    accidentChecklist: 'Accident Checklist',
    accidentDesc: 'Step-by-step guide: what to do after an accident',
    rights: 'Your Rights During a Traffic Stop',
    rightsDesc: 'Know your rights when stopped by police',
    documents: 'Required Documents Checklist',
    documentsDesc: 'Documents to carry while driving',
    nearestStation: 'Nearest Traffic Police Station',
    nearestDesc: 'Find the closest station to your location',
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all as read',
    clearAll: 'Clear all',
    noNotifications: 'No notifications yet',
    lawChanges: 'Law Changes',
    reminders: 'Reminders',
    safetyTips: 'Safety Tips',
    appUpdates: 'App Updates',
  },
};
